pub mod api;
pub mod config;
pub mod multiplier;
pub mod node;
pub mod proxy;
pub mod subscriptions;
pub use subscriptions::{
    SubscriptionFailureKind, SubscriptionFetchOutcome, SubscriptionFetchReport,
    SubscriptionRefreshPhase, SubscriptionRefreshStatus,
};
pub mod version;

pub use api::{
    ApiResponse, ConnectivityResult, DeleteRuleRequest, MaxMultiplierRequest, McpRequest,
    NodeSelectRequest, RouteModeRequest, RuleInfo, RuleRequest, RuntimePhase, RuntimeWarning,
    RuntimeWarningSeverity, ScheduledRefreshRequest, ScheduledRefreshStatus,
    SetNodeDisabledRequest, StatusData, SubBatchRequest, SubBatchResult, SubNodeInfo, SubNodesInfo,
    SubRequest, SubStatus, SubscriptionState, VergeImportItem, VergeImportResult,
};
#[cfg(not(windows))]
pub use api::{VpsDeployRequest, VpsDeployResponse};
pub use config::{
    Config, DisabledNode, NodeSelect, Region, RouteMode, ScheduledRefresh, StableConfig,
    VolatileConfig, DEFAULT_PORT,
};
pub use multiplier::{node_multiplier, NodeMultiplier};
pub use node::{
    BatchNodeAdded, BatchNodeFailure, BatchNodeRequest, BatchNodeResult, DeleteNodeRequest,
    NodeInfo, NodeRequest,
};
#[cfg(not(windows))]
pub use node::{Hysteria2, Hysteria2Obfs, Tls};
pub use proxy::{LastProxy, SwitchProxyResult};
#[cfg(any(not(windows), test))]
pub use version::GitHubAsset;
pub use version::{GitHubRelease, VersionInfo};

#[cfg(all(test, not(windows)))]
mod typescript_contract {
    use std::fmt::Write as _;
    use std::path::PathBuf;

    use ts_rs::{Config as TsConfig, TS};

    use super::*;

    const GENERATED_HEADER: &str = "// @generated by scripts/generate-api-types.sh; DO NOT EDIT.\n\
// Rust serde models in crates/miao-core are the source of truth.\n\n";

    fn push_decl<T: TS>(output: &mut String, config: &TsConfig) {
        let declaration = T::decl(config);
        let mut lines = declaration.lines();
        if let Some(first) = lines.next() {
            writeln!(output, "export {}", first.trim_end()).expect("write to string");
        }
        for line in lines {
            writeln!(output, "{}", line.trim_end()).expect("write to string");
        }
        output.push('\n');
    }

    fn generated_typescript() -> String {
        let config = TsConfig::new().with_large_int("number");
        let mut output = String::from(GENERATED_HEADER);

        let node_types = crate::validation::VALID_NODE_TYPES
            .iter()
            .map(|kind| format!("'{kind}'"))
            .collect::<Vec<_>>()
            .join(" | ");
        writeln!(output, "export type NodeType = {node_types};\n").expect("write to string");

        push_decl::<RouteMode>(&mut output, &config);
        push_decl::<NodeSelect>(&mut output, &config);
        push_decl::<RuntimePhase>(&mut output, &config);
        push_decl::<SubscriptionFailureKind>(&mut output, &config);
        push_decl::<SubscriptionFetchOutcome>(&mut output, &config);
        push_decl::<SubscriptionFetchReport>(&mut output, &config);
        push_decl::<SubscriptionRefreshPhase>(&mut output, &config);
        push_decl::<SubscriptionRefreshStatus>(&mut output, &config);
        push_decl::<crate::services::commands::subs::SubscriptionRefreshResult>(&mut output, &config);
        push_decl::<RuntimeWarningSeverity>(&mut output, &config);
        push_decl::<RuntimeWarning>(&mut output, &config);
        push_decl::<ApiResponse<()>>(&mut output, &config);
        push_decl::<StatusData>(&mut output, &config);
        push_decl::<ConnectivityResult>(&mut output, &config);
        push_decl::<NodeInfo>(&mut output, &config);
        push_decl::<RuleInfo>(&mut output, &config);
        push_decl::<SubscriptionState>(&mut output, &config);
        push_decl::<SubStatus>(&mut output, &config);
        push_decl::<SubNodeInfo>(&mut output, &config);
        push_decl::<SubNodesInfo>(&mut output, &config);
        push_decl::<SetNodeDisabledRequest>(&mut output, &config);
        push_decl::<VersionInfo>(&mut output, &config);
        push_decl::<SubRequest>(&mut output, &config);
        push_decl::<VergeImportItem>(&mut output, &config);
        push_decl::<VergeImportResult>(&mut output, &config);
        push_decl::<SubBatchRequest>(&mut output, &config);
        push_decl::<SubBatchResult>(&mut output, &config);
        push_decl::<RuleRequest>(&mut output, &config);
        push_decl::<DeleteRuleRequest>(&mut output, &config);
        push_decl::<McpRequest>(&mut output, &config);
        push_decl::<ScheduledRefreshRequest>(&mut output, &config);
        push_decl::<ScheduledRefreshStatus>(&mut output, &config);
        push_decl::<RouteModeRequest>(&mut output, &config);
        push_decl::<NodeSelectRequest>(&mut output, &config);
        push_decl::<MaxMultiplierRequest>(&mut output, &config);
        push_decl::<LastProxy>(&mut output, &config);
        push_decl::<SwitchProxyResult>(&mut output, &config);
        push_decl::<VpsDeployRequest>(&mut output, &config);
        push_decl::<VpsDeployResponse>(&mut output, &config);
        push_decl::<NodeRequest>(&mut output, &config);
        push_decl::<BatchNodeRequest>(&mut output, &config);
        push_decl::<BatchNodeAdded>(&mut output, &config);
        push_decl::<BatchNodeFailure>(&mut output, &config);
        push_decl::<BatchNodeResult>(&mut output, &config);
        push_decl::<DeleteNodeRequest>(&mut output, &config);

        while output.ends_with("\n\n") {
            output.pop();
        }
        output
    }

    fn binding_path() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../frontend-rsbuild/src/types/api.ts")
    }

    #[test]
    fn typescript_api_bindings_are_current() {
        let path = binding_path();
        let actual = std::fs::read_to_string(&path)
            .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
        assert_eq!(
            actual,
            generated_typescript(),
            "TypeScript API bindings are stale; run ./scripts/generate-api-types.sh"
        );
    }

    #[test]
    #[ignore = "writes the tracked TypeScript API binding"]
    fn export_typescript_api_bindings() {
        let path = binding_path();
        std::fs::write(&path, generated_typescript())
            .unwrap_or_else(|err| panic!("failed to write {}: {err}", path.display()));
    }
}
