use sha2::{Digest, Sha256};
use std::collections::{HashMap, HashSet};
use std::path::Path;
use std::sync::atomic::{AtomicU64, Ordering};
use tokio::io::AsyncWriteExt;
use tracing::{error, info, warn};

use std::sync::Arc;

use crate::error::{AppError, AppResult};
#[cfg(test)]
use crate::models::StableConfig;
use crate::models::{Config, NodeMultiplier, NodeSelect, ScheduledRefresh, VolatileConfig};
use crate::state::AppState;

const CACHE_MANIFEST_VERSION: u32 = 1;
/// Bump only when generated sing-box semantics become incompatible with old
/// cached bytes. Package releases alone do not invalidate a healthy cache.
/// Version 2 excludes informational pseudo-nodes from subscription outbounds.
// Version 3 derives regional candidates from current metadata, not stable tags.
const RUNTIME_CONFIG_SCHEMA_VERSION: u32 = 3;

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
struct CacheManifest {
    manifest_version: u32,
    runtime_schema_version: u32,
    input_sha256: String,
    cache_sha256: String,
    verified: bool,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum CacheCompatibility {
    Verified,
    Legacy,
    Incompatible(String),
}

fn sha256_hex(bytes: &[u8]) -> String {
    hex::encode(Sha256::digest(bytes))
}

fn runtime_input_sha256(config: &Config) -> AppResult<String> {
    // disabled_nodes is semantically a set: ordering and duplicate entries do
    // not change generated bytes, so normalize it before binding the cache.
    let mut disabled_nodes: Vec<(&str, &str)> = config
        .disabled_nodes
        .iter()
        .map(|entry| (entry.sub.as_str(), entry.name.as_str()))
        .collect();
    disabled_nodes.sort_unstable();
    disabled_nodes.dedup();

    let mut value = serde_json::json!({
        "subs": &config.subs,
        "nodes": &config.nodes,
        "custom_rules": &config.custom_rules,
        "node_select": config.node_select.as_str(),
        "route_mode": match config.route_mode {
            crate::models::RouteMode::Rule => "rule",
            crate::models::RouteMode::Global => "global",
        },
    });
    // Keep the original v1 hash for the common empty-set case so existing
    // verified caches remain eligible after upgrading. A non-empty set always
    // changes the hash and therefore cannot accept a cache that predates it.
    if !disabled_nodes.is_empty() {
        value["disabled_nodes"] = serde_json::json!(disabled_nodes);
    }
    // 最高倍率仅影响自动 urltest 候选；manual 缓存与倍率偏好无关。
    // None 保持旧版输入哈希，既有“不限倍率”缓存无需因功能升级失效。
    if !config.node_select.is_manual() {
        if let Some(max_multiplier) = config.max_multiplier {
            value["max_multiplier"] = serde_json::json!(max_multiplier.as_config_value());
        }
    }
    Ok(sha256_hex(&serde_json::to_vec(&value)?))
}

pub async fn cache_compatibility(state: &AppState, config: &Config) -> CacheCompatibility {
    let cache = match tokio::fs::read(&state.runtime_paths.config_cache).await {
        Ok(bytes) if !bytes.is_empty() => bytes,
        Ok(_) => return CacheCompatibility::Incompatible("cache is empty".to_string()),
        Err(err) => return CacheCompatibility::Incompatible(format!("cache unavailable: {err}")),
    };
    let manifest_bytes = match tokio::fs::read(&state.runtime_paths.cache_manifest).await {
        Ok(bytes) => bytes,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => {
            return CacheCompatibility::Legacy;
        }
        Err(err) => {
            return CacheCompatibility::Incompatible(format!("manifest unavailable: {err}"));
        }
    };
    let manifest: CacheManifest = match serde_json::from_slice(&manifest_bytes) {
        Ok(manifest) => manifest,
        Err(err) => {
            return CacheCompatibility::Incompatible(format!("manifest is invalid: {err}"));
        }
    };
    if !manifest.verified {
        return CacheCompatibility::Incompatible(
            "legacy cache was already accepted once and remains unverified".to_string(),
        );
    }
    if manifest.manifest_version != CACHE_MANIFEST_VERSION
        || manifest.runtime_schema_version != RUNTIME_CONFIG_SCHEMA_VERSION
    {
        return CacheCompatibility::Incompatible("cache schema is incompatible".to_string());
    }
    if manifest.cache_sha256 != sha256_hex(&cache) {
        return CacheCompatibility::Incompatible("cache content hash does not match".to_string());
    }
    let input = match runtime_input_sha256(config) {
        Ok(input) => input,
        Err(err) => {
            return CacheCompatibility::Incompatible(format!(
                "failed to hash runtime inputs: {err}"
            ));
        }
    };
    if manifest.input_sha256 != input {
        return CacheCompatibility::Incompatible(
            "cache was generated from different configuration inputs".to_string(),
        );
    }
    CacheCompatibility::Verified
}

async fn write_cache_manifest(state: &AppState, verified: bool) -> AppResult<()> {
    let cache = tokio::fs::read(&state.runtime_paths.config_cache)
        .await
        .map_err(|e| AppError::context("Failed to read config cache for manifest", e))?;
    let config = state.config.read().await.clone();
    let manifest = CacheManifest {
        manifest_version: CACHE_MANIFEST_VERSION,
        runtime_schema_version: RUNTIME_CONFIG_SCHEMA_VERSION,
        input_sha256: runtime_input_sha256(&config)?,
        cache_sha256: sha256_hex(&cache),
        verified,
    };
    write_file_atomic(
        &state.runtime_paths.cache_manifest,
        &serde_json::to_vec(&manifest)?,
    )
    .await
}

pub async fn mark_legacy_cache_used(state: &AppState) {
    if let Err(err) = write_cache_manifest(state, false).await {
        warn!(error = %err, "Failed to record legacy cache migration marker");
    }
}

pub(super) fn config_cache_path(state: &AppState) -> &Path {
    &state.runtime_paths.config_cache
}

/// Last explicitly selected strategy. Unlike the effective volatile value,
/// this is not rewritten when an unavailable region temporarily falls back to
/// manual mode.
pub async fn load_node_select_preference(path: &Path) -> Option<NodeSelect> {
    let content = tokio::fs::read_to_string(path).await.ok()?;
    NodeSelect::parse(content.trim())
}

pub async fn save_node_select_preference(
    state: &AppState,
    node_select: NodeSelect,
) -> AppResult<()> {
    let content = format!("{}\n", node_select.as_str());
    let path = &state.runtime_paths.node_select_preference;
    if tokio::fs::read(path)
        .await
        .is_ok_and(|existing| existing == content.as_bytes())
    {
        return Ok(());
    }
    write_file_transactional(path, content.as_bytes()).await
}

/// 外层 Option 区分“偏好文件不存在/损坏”和“用户明确选择不限”。
pub async fn load_max_multiplier_preference(path: &Path) -> Option<Option<NodeMultiplier>> {
    let content = tokio::fs::read_to_string(path).await.ok()?;
    let value = content.trim();
    if value == "unlimited" {
        return Some(None);
    }
    NodeMultiplier::parse(value).map(Some)
}

pub async fn save_max_multiplier_preference(
    state: &AppState,
    max_multiplier: Option<NodeMultiplier>,
) -> AppResult<()> {
    let content = max_multiplier
        .map(|value| value.as_config_value())
        .unwrap_or_else(|| "unlimited".to_string())
        + "\n";
    let path = &state.runtime_paths.max_multiplier_preference;
    if tokio::fs::read(path)
        .await
        .is_ok_and(|existing| existing == content.as_bytes())
    {
        return Ok(());
    }
    write_file_transactional(path, content.as_bytes()).await
}

/// 原子写入文件：先写入临时文件，再重命名为目标文件
pub(crate) async fn write_file_atomic(path: &Path, content: &[u8]) -> AppResult<()> {
    write_file_atomic_inner(path, content, false).await
}

async fn write_file_atomic_inner(
    path: &Path,
    content: &[u8],
    #[cfg_attr(not(test), allow(unused_variables))] fail_directory_sync: bool,
) -> AppResult<()> {
    let parent = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."));
    tokio::fs::create_dir_all(parent)
        .await
        .map_err(|e| AppError::context("Failed to create config directory", e))?;

    static TEMP_ID: AtomicU64 = AtomicU64::new(0);
    let id = TEMP_ID.fetch_add(1, Ordering::Relaxed);
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("miao-state");
    let temp_path = parent.join(format!(".{file_name}.tmp.{}.{}", std::process::id(), id));

    let result = async {
        let mut file = tokio::fs::OpenOptions::new()
            .create_new(true)
            .write(true)
            .open(&temp_path)
            .await
            .map_err(|e| AppError::context("Failed to create temp file", e))?;
        file.write_all(content)
            .await
            .map_err(|e| AppError::context("Failed to write temp file", e))?;
        file.flush()
            .await
            .map_err(|e| AppError::context("Failed to flush temp file", e))?;
        file.sync_all()
            .await
            .map_err(|e| AppError::context("Failed to sync temp file", e))?;
        drop(file);
        tokio::fs::rename(&temp_path, path)
            .await
            .map_err(|e| AppError::context("Failed to atomically rename file", e))?;

        #[cfg(unix)]
        {
            #[cfg(test)]
            if fail_directory_sync {
                return Err(AppError::message(
                    "File was replaced, but failed to sync config directory: injected failure",
                ));
            }
            let parent = parent.to_path_buf();
            tokio::task::spawn_blocking(move || std::fs::File::open(parent)?.sync_all())
                .await
                .map_err(|e| {
                    AppError::message(format!(
                        "File was replaced, but failed to join directory sync: {e}"
                    ))
                })?
                .map_err(|e| {
                    AppError::context("File was replaced, but failed to sync config directory", e)
                })?;
        }
        Ok(())
    }
    .await;
    if result.is_err() {
        let _ = tokio::fs::remove_file(&temp_path).await;
    }
    result
}

#[cfg(test)]
async fn save_yaml_to(path: &Path, value: &impl serde::Serialize) -> AppResult<()> {
    save_yaml_to_inner(path, value, false).await
}

async fn save_yaml_to_inner(
    path: &Path,
    value: &impl serde::Serialize,
    #[cfg_attr(not(test), allow(unused_variables))] fail_directory_sync: bool,
) -> AppResult<()> {
    let yaml = yaml_serde::to_string(value)?;
    if let Ok(existing) = tokio::fs::read_to_string(path).await {
        if existing == yaml {
            info!(path = ?path, "File already up to date, skipping write");
            return Ok(());
        }
    }

    write_file_atomic_inner(path, yaml.as_bytes(), fail_directory_sync).await
}

async fn snapshot_file(path: &Path, label: &str) -> AppResult<Option<Vec<u8>>> {
    match tokio::fs::read(path).await {
        Ok(bytes) => Ok(Some(bytes)),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(err) => Err(AppError::context(
            format!("Failed to snapshot {label}"),
            err,
        )),
    }
}

async fn restore_file(path: &Path, snapshot: &Option<Vec<u8>>) -> AppResult<()> {
    match snapshot {
        Some(bytes) => write_file_atomic(path, bytes).await,
        None => remove_file_durable(path).await,
    }
}

/// A failed directory fsync may follow a successful rename. Restore the
/// original destination before reporting any write failure.
async fn write_file_transactional(path: &Path, content: &[u8]) -> AppResult<()> {
    let old = snapshot_file(path, "file before save").await?;
    if old.as_deref() == Some(content) {
        return Ok(());
    }
    if let Err(write_err) = write_file_atomic(path, content).await {
        return match restore_file(path, &old).await {
            Ok(()) => Err(write_err),
            Err(rollback_err) => Err(AppError::message(format!(
                "{write_err}. File rollback also failed: {rollback_err}"
            ))),
        };
    }
    Ok(())
}

#[cfg(test)]
pub async fn save_config_to(path: &Path, config: &Config) -> AppResult<()> {
    save_stable_to(path, &StableConfig::from(config)).await
}

#[cfg(test)]
pub async fn save_stable_to(path: &Path, config: &StableConfig) -> AppResult<()> {
    save_yaml_to(path, config).await
}

/// 读取指定路径的易变层配置；文件缺失、读不出、内容损坏都返回 `None`
/// （调用方保留 config.yaml 的解析结果，见 `StableConfig::effective`）。
pub async fn load_volatile_config_at(path: &Path) -> Option<VolatileConfig> {
    let content = tokio::fs::read_to_string(path).await.ok()?;
    yaml_serde::from_str(&content).ok()
}

#[cfg(test)]
pub async fn save_volatile_to(path: &Path, volatile: &VolatileConfig) -> AppResult<()> {
    save_yaml_to(path, volatile).await
}

/// 配置分层落盘：稳定层（config.yaml）+ 易变层（volatile.yaml）。
/// 两层各自原子写并按内容跳过未变写入——单一层面的变更只产生一层的 I/O。
/// 跨文件无原子性：稳定层写成功而易变层失败时，把稳定层回写旧内容
/// 并准确报告补偿结果，避免把撕裂状态误报成普通写入失败。
pub async fn save_config_layered(state: &Arc<AppState>, config: &Config) -> AppResult<()> {
    save_config_layered_inner(state, config, false, false, false).await
}

async fn save_config_layered_inner(
    state: &Arc<AppState>,
    config: &Config,
    #[cfg_attr(not(test), allow(unused_variables))] fail_stable_sync: bool,
    #[cfg_attr(not(test), allow(unused_variables))] fail_volatile_sync: bool,
    #[cfg_attr(not(test), allow(unused_variables))] fail_rollback: bool,
) -> AppResult<()> {
    // Both snapshots must be available before either file can change.
    let old_stable = snapshot_file(&state.config_path, "stable config before layered save").await?;
    let old_volatile =
        snapshot_file(&state.volatile_path, "volatile config before layered save").await?;

    let stable = state
        .stable_config
        .read()
        .await
        .with_stable_fields_from(config);
    let write_result = async {
        save_yaml_to_inner(&state.config_path, &stable, fail_stable_sync).await?;
        save_yaml_to_inner(
            &state.volatile_path,
            &VolatileConfig::from(config),
            fail_volatile_sync,
        )
        .await
    }
    .await;
    if let Err(write_err) = write_result {
        let mut rollback_errors = Vec::new();
        #[cfg(test)]
        if fail_rollback {
            rollback_errors.push("stable config: injected rollback failure".to_string());
        } else if let Err(err) = restore_file(&state.config_path, &old_stable).await {
            rollback_errors.push(format!("stable config: {err}"));
        }
        #[cfg(not(test))]
        if let Err(err) = restore_file(&state.config_path, &old_stable).await {
            rollback_errors.push(format!("stable config: {err}"));
        }
        if let Err(err) = restore_file(&state.volatile_path, &old_volatile).await {
            rollback_errors.push(format!("volatile config: {err}"));
        }
        let message = if rollback_errors.is_empty() {
            format!("Failed to save layered config: {write_err}; both config files were restored")
        } else {
            format!(
                "Failed to save layered config: {write_err}. Rollback failures: {}",
                rollback_errors.join("; ")
            )
        };
        return Err(AppError::message(message));
    }
    *state.stable_config.write().await = stable;
    Ok(())
}

async fn remove_file_durable(path: &Path) -> AppResult<()> {
    match tokio::fs::remove_file(path).await {
        Ok(()) => {}
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(err) => return Err(AppError::context("Failed to remove stable config", err)),
    }
    #[cfg(unix)]
    {
        let parent = path
            .parent()
            .filter(|parent| !parent.as_os_str().is_empty())
            .unwrap_or_else(|| Path::new("."))
            .to_path_buf();
        tokio::task::spawn_blocking(move || std::fs::File::open(parent)?.sync_all())
            .await
            .map_err(|err| {
                AppError::message(format!(
                    "Stable config was removed, but failed to join directory sync: {err}"
                ))
            })?
            .map_err(|err| {
                AppError::context(
                    "Stable config was removed, but failed to sync config directory",
                    err,
                )
            })?;
    }
    Ok(())
}

/// Persist only the stable fields. Used by settings such as MCP that do not
/// affect sing-box or the volatile runtime preferences.
pub async fn save_stable_fields(state: &Arc<AppState>, config: &Config) -> AppResult<()> {
    let stable = state
        .stable_config
        .read()
        .await
        .with_stable_fields_from(config);
    let yaml = yaml_serde::to_string(&stable)?;
    write_file_transactional(&state.config_path, yaml.as_bytes()).await?;
    *state.stable_config.write().await = stable;
    Ok(())
}

/// 保存定时刷新设置（稳定层 config.yaml）。调用方须持有 `config_update`。
pub async fn save_scheduled_refresh(
    state: &Arc<AppState>,
    scheduled_refresh: ScheduledRefresh,
) -> AppResult<()> {
    let stable = state
        .stable_config
        .read()
        .await
        .with_scheduled_refresh(scheduled_refresh);
    let yaml = yaml_serde::to_string(&stable)?;
    write_file_transactional(&state.config_path, yaml.as_bytes()).await?;
    *state.stable_config.write().await = stable;
    Ok(())
}

/// 筛空地区后把内存里的 node_select 写回 manual。
/// node_select 是易变层字段：稳定层 YAML 序列化时天然不含它，
/// 这里走分层落盘（稳定层内容未变会被跳过，实际只写易变层）。
pub async fn persist_effective_node_select(
    state: &Arc<AppState>,
    node_select: NodeSelect,
) -> AppResult<()> {
    let mut config = state.config.read().await.clone();
    if config.node_select == node_select {
        return Ok(());
    }
    config.node_select = node_select;
    save_config_layered(state, &config).await?;
    *state.config.write().await = config;
    Ok(())
}

pub async fn save_config_cache(state: &AppState) {
    if let Err(err) =
        save_config_cache_at(&state.runtime_paths.active_config, config_cache_path(state)).await
    {
        error!(error = %err, "Failed to save config cache");
        return;
    }
    if let Err(err) = write_cache_manifest(state, true).await {
        error!(error = %err, "Failed to save config cache manifest");
    }
}

/// 原子保存：读当前 config.json 字节，经临时文件 rename 落 cache。
/// 进程在 copy 中途被杀不会留下半截 cache（回滚/启动快速通道会把它当好配置用）。
async fn save_config_cache_at(config_path: &Path, cache_path: &Path) -> AppResult<()> {
    let bytes = tokio::fs::read(config_path)
        .await
        .map_err(|e| AppError::context("Failed to read runtime config for cache", e))?;
    write_file_atomic(cache_path, &bytes).await?;
    info!(path = %cache_path.display(), "Config cache saved");
    Ok(())
}

/// 上次成功运行的生成配置缓存是否存在（启动快速通道的入场券）
pub fn has_config_cache(state: &AppState) -> bool {
    config_cache_path(state).exists()
}

/// 读取缓存内容，用于订阅刷新后的变更比对
pub async fn read_config_cache(state: &AppState) -> Option<Vec<u8>> {
    tokio::fs::read(config_cache_path(state)).await.ok()
}

pub async fn restore_config_from_cache(state: &AppState) -> AppResult<()> {
    restore_config_from_cache_at(config_cache_path(state), &state.runtime_paths.active_config).await
}

async fn restore_config_from_cache_at(cache_path: &Path, config_path: &Path) -> AppResult<()> {
    if !cache_path.exists() {
        return Err(AppError::message("No cached config available"));
    }
    let bytes = tokio::fs::read(cache_path)
        .await
        .map_err(|e| AppError::context("Failed to read config cache", e))?;
    if bytes.is_empty() {
        return Err(AppError::message("Cached config is empty"));
    }
    write_file_atomic(config_path, &bytes).await?;
    info!(path = %cache_path.display(), "Restored config from cache");
    Ok(())
}

/// 配置变更前把当前 config.json 的字节读进内存：回滚 tier 1 材料。
/// 它正在跑/刚跑过，必然已知可用；文件不在、读不出或为空都视为没有快照。
pub async fn snapshot_runtime_config(state: &AppState) -> Option<Vec<u8>> {
    snapshot_runtime_config_at(&state.runtime_paths.active_config).await
}

async fn snapshot_runtime_config_at(path: &Path) -> Option<Vec<u8>> {
    tokio::fs::read(path)
        .await
        .ok()
        .filter(|bytes| !bytes.is_empty())
}

/// 把快照字节原子写回 config.json：回滚是纯本地文件操作，不碰网络。
pub async fn restore_runtime_config_bytes(state: &AppState, bytes: &[u8]) -> AppResult<()> {
    restore_runtime_config_bytes_at(&state.runtime_paths.active_config, bytes).await
}

async fn restore_runtime_config_bytes_at(path: &Path, bytes: &[u8]) -> AppResult<()> {
    write_file_atomic(path, bytes).await
}

/// 订阅节点集快照：上次真拉取拿到的节点，供本地语义变更（节点选择/路由模式/
/// 规则/手动节点）零网络重建配置。`subs` 是一致性护栏：与当前配置的
/// 订阅列表不一致时快照作废（订阅增删后必须真拉取一次重建快照）。
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub struct SubNodesSnapshot {
    #[serde(default)]
    pub version: u32,
    pub subs: Vec<String>,
    pub node_names: Vec<String>,
    pub outbounds: Vec<serde_json::Value>,
    #[serde(default)]
    pub source_ids: Vec<String>,
}

/// Immutable read projection. The full JSON and informational-node filtering
/// are parsed once per snapshot, rather than on every panel poll.
pub struct SubNodesReadModel {
    snapshot: SubNodesSnapshot,
    pub live_names: HashMap<String, HashSet<String>>,
}
impl std::ops::Deref for SubNodesReadModel {
    type Target = SubNodesSnapshot;
    fn deref(&self) -> &Self::Target {
        &self.snapshot
    }
}
impl SubNodesReadModel {
    fn new(snapshot: SubNodesSnapshot) -> Self {
        let mut live_names: HashMap<String, HashSet<String>> = HashMap::new();
        for ((source, name), outbound) in snapshot
            .source_ids
            .iter()
            .zip(&snapshot.node_names)
            .zip(&snapshot.outbounds)
        {
            if !crate::services::subscription::is_informational_subscription_node(name, outbound) {
                live_names
                    .entry(source.clone())
                    .or_default()
                    .insert(name.clone());
            }
        }
        Self {
            snapshot,
            live_names,
        }
    }
}

impl SubNodesSnapshot {
    /// 快照能否服务于当前订阅列表
    pub fn matches_subs(&self, subs: &[String]) -> bool {
        self.subs == subs
    }

    pub fn from_fetched_nodes(subs: Vec<String>, nodes: Vec<super::generate::FetchedNode>) -> Self {
        let mut node_names = Vec::with_capacity(nodes.len());
        let mut outbounds = Vec::with_capacity(nodes.len());
        let mut source_ids = Vec::with_capacity(nodes.len());
        for node in nodes {
            node_names.push(node.name);
            outbounds.push(node.outbound);
            source_ids.push(node.source_id);
        }
        Self {
            version: 1,
            subs,
            node_names,
            outbounds,
            source_ids,
        }
    }

    pub fn to_fetched_nodes(&self) -> Vec<super::generate::FetchedNode> {
        self.node_names
            .iter()
            .zip(&self.outbounds)
            .enumerate()
            .map(|(index, (name, outbound))| super::generate::FetchedNode {
                source_id: self
                    .source_ids
                    .get(index)
                    .cloned()
                    .unwrap_or_else(|| "legacy".to_string()),
                name: name.clone(),
                outbound: outbound.clone(),
            })
            .collect()
    }
}

fn sub_nodes_snapshot_path(state: &AppState) -> &Path {
    &state.runtime_paths.sub_nodes_snapshot
}

pub fn has_sub_nodes_snapshot(state: &AppState) -> bool {
    sub_nodes_snapshot_path(state).exists()
}

pub async fn save_sub_nodes_snapshot(
    state: &AppState,
    snapshot: &SubNodesSnapshot,
) -> AppResult<()> {
    let mut cached = state.sub_nodes_cache.write().await;
    save_sub_nodes_snapshot_at(sub_nodes_snapshot_path(state), snapshot).await?;
    *cached = Some(Arc::new(SubNodesReadModel::new(snapshot.clone())));
    state.data_revision.fetch_add(1, Ordering::Relaxed);
    Ok(())
}

async fn save_sub_nodes_snapshot_at(path: &Path, snapshot: &SubNodesSnapshot) -> AppResult<()> {
    let bytes = serde_json::to_vec(snapshot)?;
    // 秒开 + 订阅无变化的启动也会触发记录：内容一致就跳过，
    // 避免每次开机把可能 MB 级的快照白写一遍
    if let Ok(existing) = tokio::fs::read(path).await {
        if existing == bytes {
            return Ok(());
        }
    }
    write_file_atomic(path, &bytes).await
}

/// 读取快照；文件缺失、读不出、内容损坏都视为没有快照（调用方退化到拉取路径）
pub async fn read_sub_nodes_snapshot(state: &AppState) -> Option<Arc<SubNodesReadModel>> {
    if let Some(snapshot) = state.sub_nodes_cache.read().await.as_ref() {
        return Some(snapshot.clone());
    }
    // Serialize the initial load with writers so an older disk read cannot
    // replace a freshly committed in-memory snapshot.
    let mut cached = state.sub_nodes_cache.write().await;
    if cached.is_none() {
        *cached = read_sub_nodes_snapshot_at(sub_nodes_snapshot_path(state))
            .await
            .map(SubNodesReadModel::new)
            .map(Arc::new);
    }
    cached.clone()
}

async fn read_sub_nodes_snapshot_at(path: &Path) -> Option<SubNodesSnapshot> {
    let bytes = tokio::fs::read(path).await.ok()?;
    serde_json::from_slice(&bytes).ok()
}

#[cfg(test)]
mod tests {
    use super::{
        load_max_multiplier_preference, load_node_select_preference, load_volatile_config_at,
        persist_effective_node_select, read_sub_nodes_snapshot_at, restore_config_from_cache_at,
        restore_runtime_config_bytes_at, save_config_cache_at, save_config_layered,
        save_config_layered_inner, save_max_multiplier_preference, save_node_select_preference,
        save_sub_nodes_snapshot_at, save_volatile_to, snapshot_runtime_config_at,
        write_file_atomic_inner, SubNodesSnapshot,
    };
    use crate::services::singbox::get_sing_box_home;

    #[test]
    fn config_cache_lives_under_sing_box_home() {
        let paths = crate::paths::RuntimePaths::new(
            get_sing_box_home(),
            std::path::Path::new("config.yaml"),
        );
        assert_eq!(
            paths.config_cache,
            get_sing_box_home().join("config.json.cache")
        );
    }

    #[tokio::test]
    async fn volatile_config_roundtrip_and_fallbacks() {
        use crate::models::{NodeSelect, Region, RouteMode, VolatileConfig};

        let temp_dir = std::env::temp_dir().join(format!("miao-volatile-{}", std::process::id()));
        let path = temp_dir.join("volatile.yaml");
        tokio::fs::create_dir_all(&temp_dir).await.unwrap();

        // 缺失 / 损坏都读不出（None = 不覆盖 config.yaml）
        assert!(load_volatile_config_at(&path).await.is_none());
        tokio::fs::write(&path, b"route_mode: [not-a-mode]")
            .await
            .unwrap();
        assert!(load_volatile_config_at(&path).await.is_none());

        let volatile = VolatileConfig {
            node_select: NodeSelect::Fastest(Region::Sg),
            route_mode: RouteMode::Global,
            ..VolatileConfig::default()
        };
        save_volatile_to(&path, &volatile).await.unwrap();
        assert!(!temp_dir.join("volatile.tmp").exists());
        let loaded = load_volatile_config_at(&path).await.unwrap();
        assert_eq!(loaded, volatile);

        // 未变化时跳过写入：内容不变且不产生临时文件
        save_volatile_to(&path, &volatile).await.unwrap();
        assert!(!temp_dir.join("volatile.tmp").exists());

        let _ = tokio::fs::remove_dir_all(&temp_dir).await;
    }

    #[cfg(unix)]
    #[tokio::test]
    async fn atomic_write_reports_that_rename_committed_before_directory_sync_failure() {
        let temp_dir = tempfile::tempdir().unwrap();
        let path = temp_dir.path().join("state");
        tokio::fs::write(&path, b"old").await.unwrap();

        let err = write_file_atomic_inner(&path, b"new", true)
            .await
            .unwrap_err();

        assert!(err.to_string().contains("File was replaced"));
        assert_eq!(tokio::fs::read(&path).await.unwrap(), b"new");
    }

    #[tokio::test]
    async fn save_config_layered_does_not_treat_snapshot_read_failure_as_missing() {
        use crate::models::Config;
        use crate::state::AppState;

        let temp_dir = tempfile::tempdir().unwrap();
        let config_path = temp_dir.path().join("config.yaml");
        tokio::fs::create_dir(&config_path).await.unwrap();
        let state = std::sync::Arc::new(
            AppState::with_config_path(
                Config::default(),
                config_path.clone(),
                temp_dir.path().join("volatile.yaml"),
            )
            .unwrap(),
        );

        let err = save_config_layered(&state, &Config::default())
            .await
            .unwrap_err();

        assert!(err
            .to_string()
            .contains("Failed to snapshot stable config before layered save"));
        assert!(config_path.is_dir());
    }

    #[cfg(unix)]
    #[tokio::test]
    async fn save_config_layered_restores_both_files_and_memory_after_post_rename_failure() {
        use crate::models::{Config, NodeSelect, Region};
        use crate::state::AppState;

        let base = std::env::temp_dir().join(format!(
            "miao-layered-fail-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        tokio::fs::create_dir_all(&base).await.unwrap();
        let config_path = base.join("config.yaml");
        let volatile_path = base.join("volatile.yaml");
        let old_config = Config::default();
        let new_config = Config {
            subs: vec!["https://a.example.com".to_string()],
            node_select: NodeSelect::Fastest(Region::Hk),
            ..Config::default()
        };

        let old_yaml = "subs:\n- https://old.example.com\n";
        let old_volatile = "node_select: manual\nroute_mode: rule\n";
        for (fail_stable, fail_volatile) in [(true, false), (false, true)] {
            tokio::fs::write(&config_path, old_yaml).await.unwrap();
            tokio::fs::write(&volatile_path, old_volatile)
                .await
                .unwrap();
            let state = std::sync::Arc::new(
                AppState::with_config_path(
                    old_config.clone(),
                    config_path.clone(),
                    volatile_path.clone(),
                )
                .unwrap(),
            );

            let err =
                save_config_layered_inner(&state, &new_config, fail_stable, fail_volatile, false)
                    .await
                    .unwrap_err();
            assert!(err.to_string().contains("both config files were restored"));
            assert_eq!(
                tokio::fs::read(&config_path).await.unwrap(),
                old_yaml.as_bytes()
            );
            assert_eq!(
                tokio::fs::read(&volatile_path).await.unwrap(),
                old_volatile.as_bytes()
            );
            assert_eq!(*state.config.read().await, old_config);
            assert_eq!(
                *state.stable_config.read().await,
                crate::models::StableConfig::from(&old_config)
            );
        }

        let _ = tokio::fs::remove_dir_all(&base).await;
    }

    #[cfg(unix)]
    #[tokio::test]
    async fn layered_post_rename_failure_removes_previously_absent_files() {
        for (fail_stable, fail_volatile) in [(true, false), (false, true)] {
            let temp = tempfile::tempdir().unwrap();
            let stable = temp.path().join("config.yaml");
            let volatile = temp.path().join("volatile.yaml");
            let state = std::sync::Arc::new(
                crate::state::AppState::with_config_path(
                    crate::models::Config::default(),
                    stable.clone(),
                    volatile.clone(),
                )
                .unwrap(),
            );
            let changed = crate::models::Config {
                mcp: true,
                ..crate::models::Config::default()
            };
            let error =
                save_config_layered_inner(&state, &changed, fail_stable, fail_volatile, false)
                    .await
                    .unwrap_err();
            assert!(error
                .to_string()
                .contains("both config files were restored"));
            assert!(!stable.exists());
            assert!(!volatile.exists());
            assert!(!state.stable_config.read().await.mcp);
        }
    }

    #[cfg(unix)]
    #[tokio::test]
    async fn save_config_layered_reports_primary_and_rollback_failures() {
        use crate::models::Config;
        use crate::state::AppState;

        let temp_dir = tempfile::tempdir().unwrap();
        let config_path = temp_dir.path().join("config.yaml");
        let volatile_path = temp_dir.path().join("volatile.yaml");
        tokio::fs::write(&config_path, b"mcp: false\n")
            .await
            .unwrap();
        tokio::fs::write(&volatile_path, b"node_select: manual\n")
            .await
            .unwrap();
        let state = std::sync::Arc::new(
            AppState::with_config_path(Config::default(), config_path.clone(), volatile_path)
                .unwrap(),
        );
        let changed = Config {
            mcp: true,
            ..Config::default()
        };

        let err = save_config_layered_inner(&state, &changed, false, true, true)
            .await
            .unwrap_err()
            .to_string();

        assert!(err.contains("Failed to save layered config"));
        assert!(err.contains("Rollback failures: stable config"));
        assert!(err.contains("injected rollback failure"));
        assert_ne!(
            tokio::fs::read(&config_path).await.unwrap(),
            b"mcp: false\n"
        );
    }

    #[cfg(unix)]
    #[tokio::test]
    async fn save_config_layered_skips_unchanged_stable_layer() {
        use crate::models::{Config, NodeSelect, Region};
        use crate::state::AppState;
        use std::os::unix::fs::PermissionsExt;

        // root 下权限位不生效，只读目录挡不住写入
        if nix::unistd::Uid::effective().is_root() {
            return;
        }

        let base = std::env::temp_dir().join(format!(
            "miao-layered-skip-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        let stable_dir = base.join("stable");
        tokio::fs::create_dir_all(&stable_dir).await.unwrap();
        let config_path = stable_dir.join("config.yaml");
        let volatile_path = base.join("volatile.yaml");

        let config = Config {
            subs: vec!["https://a.example.com".to_string()],
            node_select: NodeSelect::Fastest(Region::Hk),
            ..Config::default()
        };
        let state = std::sync::Arc::new(
            AppState::with_config_path(config.clone(), config_path.clone(), volatile_path.clone())
                .unwrap(),
        );
        save_config_layered(&state, &config).await.unwrap();
        let stable_bytes = tokio::fs::read(&config_path).await.unwrap();
        assert!(String::from_utf8_lossy(&stable_bytes).contains("node_select: fastest_hk"));

        // 稳定层目录设为只读：若再次尝试落盘必失败。
        // 只改易变字段（node_select），整体应成功——证明稳定层被跳过
        std::fs::set_permissions(&stable_dir, std::fs::Permissions::from_mode(0o555)).unwrap();
        let mut changed = config.clone();
        changed.node_select = NodeSelect::Fastest(Region::Jp);
        let result = save_config_layered(&state, &changed).await;
        std::fs::set_permissions(&stable_dir, std::fs::Permissions::from_mode(0o755)).unwrap();
        result.expect("stable layer must be skipped when unchanged");
        let volatile = load_volatile_config_at(&volatile_path).await.unwrap();
        assert_eq!(volatile.node_select, NodeSelect::Fastest(Region::Jp));

        let _ = tokio::fs::remove_dir_all(&base).await;
    }

    #[tokio::test]
    async fn snapshot_and_restore_roundtrip() {
        let temp_dir = std::env::temp_dir().join(format!("miao-snapshot-{}", std::process::id()));
        let config_path = temp_dir.join("config.json");
        tokio::fs::create_dir_all(&temp_dir).await.unwrap();

        // 不存在/空文件都没有快照
        assert!(snapshot_runtime_config_at(&config_path).await.is_none());
        tokio::fs::write(&config_path, b"").await.unwrap();
        assert!(snapshot_runtime_config_at(&config_path).await.is_none());

        tokio::fs::write(&config_path, br#"{"v":1}"#).await.unwrap();
        let snapshot = snapshot_runtime_config_at(&config_path).await.unwrap();

        // 模拟 apply 覆盖成新配置，回滚写回应恢复旧字节
        tokio::fs::write(&config_path, br#"{"v":2}"#).await.unwrap();
        restore_runtime_config_bytes_at(&config_path, &snapshot)
            .await
            .unwrap();
        assert_eq!(tokio::fs::read(&config_path).await.unwrap(), br#"{"v":1}"#);
        // 原子写不留下临时文件
        assert!(!temp_dir.join("config.tmp").exists());

        let _ = tokio::fs::remove_dir_all(&temp_dir).await;
    }

    #[tokio::test]
    async fn cache_save_and_restore_roundtrip() {
        let temp_dir = std::env::temp_dir().join(format!("miao-cache-{}", std::process::id()));
        let config_path = temp_dir.join("config.json");
        let cache_path = temp_dir.join("config.json.cache");
        tokio::fs::create_dir_all(&temp_dir).await.unwrap();

        tokio::fs::write(&config_path, b"good").await.unwrap();
        save_config_cache_at(&config_path, &cache_path)
            .await
            .unwrap();
        assert_eq!(tokio::fs::read(&cache_path).await.unwrap(), b"good");
        assert!(!temp_dir.join("config.json.tmp").exists());

        tokio::fs::write(&config_path, b"bad").await.unwrap();
        restore_config_from_cache_at(&cache_path, &config_path)
            .await
            .unwrap();
        assert_eq!(tokio::fs::read(&config_path).await.unwrap(), b"good");

        let _ = tokio::fs::remove_dir_all(&temp_dir).await;
    }

    #[test]
    fn cache_input_hash_normalizes_disabled_node_set() {
        use super::runtime_input_sha256;
        use crate::models::{Config, DisabledNode};

        let first = DisabledNode {
            sub: "https://a.example.com/sub".to_string(),
            name: "node-a".to_string(),
        };
        let second = DisabledNode {
            sub: "https://b.example.com/sub".to_string(),
            name: "node-b".to_string(),
        };
        let with_duplicates = Config {
            disabled_nodes: vec![second.clone(), first.clone(), first.clone()],
            ..Config::default()
        };
        let reordered = Config {
            disabled_nodes: vec![first, second],
            ..Config::default()
        };

        assert_eq!(
            runtime_input_sha256(&with_duplicates).unwrap(),
            runtime_input_sha256(&reordered).unwrap()
        );
        assert_ne!(
            runtime_input_sha256(&reordered).unwrap(),
            runtime_input_sha256(&Config::default()).unwrap()
        );
    }

    #[test]
    fn cache_input_hash_uses_multiplier_only_for_automatic_selection() {
        use super::runtime_input_sha256;
        use crate::models::{Config, NodeMultiplier, NodeSelect, Region};

        let capped_manual = Config {
            max_multiplier: NodeMultiplier::parse("2.5"),
            ..Config::default()
        };
        assert_eq!(
            runtime_input_sha256(&capped_manual).unwrap(),
            runtime_input_sha256(&Config::default()).unwrap()
        );

        let capped_automatic = Config {
            node_select: NodeSelect::Fastest(Region::Jp),
            max_multiplier: NodeMultiplier::parse("2.5"),
            ..Config::default()
        };
        let unlimited_automatic = Config {
            max_multiplier: None,
            ..capped_automatic.clone()
        };
        assert_ne!(
            runtime_input_sha256(&capped_automatic).unwrap(),
            runtime_input_sha256(&unlimited_automatic).unwrap()
        );
    }

    #[tokio::test]
    async fn cache_manifest_binds_cache_to_effective_runtime_inputs() {
        use super::{cache_compatibility, save_config_cache, CacheCompatibility};
        use crate::{models::Config, test_support::app_state};

        let state = app_state(Config {
            subs: vec!["https://a.example.com/sub".to_string()],
            ..Config::default()
        });
        tokio::fs::create_dir_all(&state.runtime_paths.runtime_dir)
            .await
            .unwrap();
        tokio::fs::write(&state.runtime_paths.active_config, br#"{"outbounds":[]}"#)
            .await
            .unwrap();
        save_config_cache(&state).await;
        assert_eq!(
            cache_compatibility(&state, &state.config.read().await.clone()).await,
            CacheCompatibility::Verified
        );

        let mut changed = state.config.read().await.clone();
        changed.custom_rules.push(
            r#"{"domain_suffix":"example.com","action":"route","outbound":"direct"}"#.to_string(),
        );
        assert!(matches!(
            cache_compatibility(&state, &changed).await,
            CacheCompatibility::Incompatible(_)
        ));

        let mut disabled_changed = state.config.read().await.clone();
        disabled_changed
            .disabled_nodes
            .push(crate::models::DisabledNode {
                sub: "https://a.example.com/sub".to_string(),
                name: "node-a".to_string(),
            });
        assert!(matches!(
            cache_compatibility(&state, &disabled_changed).await,
            CacheCompatibility::Incompatible(_)
        ));
        let _ = tokio::fs::remove_dir_all(&state.runtime_paths.runtime_dir).await;
    }

    #[tokio::test]
    async fn legacy_cache_is_accepted_only_until_migration_marker_is_written() {
        use super::{cache_compatibility, mark_legacy_cache_used, CacheCompatibility};
        use crate::{models::Config, test_support::app_state};

        let state = app_state(Config::default());
        tokio::fs::create_dir_all(&state.runtime_paths.runtime_dir)
            .await
            .unwrap();
        tokio::fs::write(&state.runtime_paths.config_cache, b"legacy")
            .await
            .unwrap();
        assert_eq!(
            cache_compatibility(&state, &Config::default()).await,
            CacheCompatibility::Legacy
        );
        mark_legacy_cache_used(&state).await;
        assert!(matches!(
            cache_compatibility(&state, &Config::default()).await,
            CacheCompatibility::Incompatible(_)
        ));
        let _ = tokio::fs::remove_dir_all(&state.runtime_paths.runtime_dir).await;
    }

    #[tokio::test]
    async fn empty_or_missing_cache_is_rejected() {
        let temp_dir =
            std::env::temp_dir().join(format!("miao-cache-empty-{}", std::process::id()));
        let config_path = temp_dir.join("config.json");
        let cache_path = temp_dir.join("config.json.cache");
        tokio::fs::create_dir_all(&temp_dir).await.unwrap();

        assert!(restore_config_from_cache_at(&cache_path, &config_path)
            .await
            .is_err());
        tokio::fs::write(&cache_path, b"").await.unwrap();
        assert!(restore_config_from_cache_at(&cache_path, &config_path)
            .await
            .is_err());

        let _ = tokio::fs::remove_dir_all(&temp_dir).await;
    }

    #[tokio::test]
    async fn sub_nodes_snapshot_roundtrip_and_guards() {
        let temp_dir =
            std::env::temp_dir().join(format!("miao-sub-snapshot-{}", std::process::id()));
        let snapshot_path = temp_dir.join("sub-nodes.json");
        tokio::fs::create_dir_all(&temp_dir).await.unwrap();

        // 缺失/损坏都读不出
        assert!(read_sub_nodes_snapshot_at(&snapshot_path).await.is_none());
        tokio::fs::write(&snapshot_path, b"not-json").await.unwrap();
        assert!(read_sub_nodes_snapshot_at(&snapshot_path).await.is_none());

        let snapshot = SubNodesSnapshot {
            version: 0,
            subs: vec!["https://a.example.com".to_string()],
            node_names: vec!["香港 01".to_string()],
            outbounds: vec![serde_json::json!({"type": "trojan", "tag": "香港 01"})],
            source_ids: vec![],
        };
        save_sub_nodes_snapshot_at(&snapshot_path, &snapshot)
            .await
            .unwrap();
        assert!(!temp_dir.join("sub-nodes.tmp").exists());

        let loaded = read_sub_nodes_snapshot_at(&snapshot_path).await.unwrap();
        assert!(loaded.matches_subs(&["https://a.example.com".to_string()]));
        assert!(!loaded.matches_subs(&["https://b.example.com".to_string()]));
        assert!(!loaded.matches_subs(&[]));
        assert_eq!(loaded.node_names, vec!["香港 01".to_string()]);

        // 内容一致时跳过重写（mtime 不变）；内容变化才真正落盘
        let mtime_before = std::fs::metadata(&snapshot_path)
            .unwrap()
            .modified()
            .unwrap();
        tokio::time::sleep(std::time::Duration::from_millis(20)).await;
        save_sub_nodes_snapshot_at(&snapshot_path, &snapshot)
            .await
            .unwrap();
        let mtime_after = std::fs::metadata(&snapshot_path)
            .unwrap()
            .modified()
            .unwrap();
        assert_eq!(
            mtime_before, mtime_after,
            "unchanged snapshot must not be rewritten"
        );

        let changed = SubNodesSnapshot {
            node_names: vec!["香港 01".to_string(), "日本 02".to_string()],
            ..snapshot.clone()
        };
        save_sub_nodes_snapshot_at(&snapshot_path, &changed)
            .await
            .unwrap();
        let reloaded = read_sub_nodes_snapshot_at(&snapshot_path).await.unwrap();
        assert_eq!(reloaded.node_names.len(), 2);

        let _ = tokio::fs::remove_dir_all(&temp_dir).await;
    }

    #[tokio::test]
    async fn node_select_preference_roundtrips_and_rejects_invalid_content() {
        use crate::models::{Config, NodeSelect, Region};
        use crate::test_support::app_state;

        let state = app_state(Config::default());
        save_node_select_preference(&state, NodeSelect::Fastest(Region::Sg))
            .await
            .unwrap();
        assert_eq!(
            load_node_select_preference(&state.runtime_paths.node_select_preference).await,
            Some(NodeSelect::Fastest(Region::Sg))
        );

        tokio::fs::write(
            &state.runtime_paths.node_select_preference,
            "not-a-strategy",
        )
        .await
        .unwrap();
        assert_eq!(
            load_node_select_preference(&state.runtime_paths.node_select_preference).await,
            None
        );
        let _ = tokio::fs::remove_dir_all(&state.runtime_paths.runtime_dir).await;
    }

    #[tokio::test]
    async fn max_multiplier_preference_distinguishes_unlimited_and_missing() {
        use crate::models::{Config, NodeMultiplier};
        use crate::test_support::app_state;

        let state = app_state(Config::default());
        let path = &state.runtime_paths.max_multiplier_preference;
        assert_eq!(load_max_multiplier_preference(path).await, None);

        let selected = NodeMultiplier::parse("6.5").unwrap();
        save_max_multiplier_preference(&state, Some(selected))
            .await
            .unwrap();
        assert_eq!(
            load_max_multiplier_preference(path).await,
            Some(Some(selected))
        );

        save_max_multiplier_preference(&state, None).await.unwrap();
        assert_eq!(load_max_multiplier_preference(path).await, Some(None));

        tokio::fs::write(path, "invalid").await.unwrap();
        assert_eq!(load_max_multiplier_preference(path).await, None);
        let _ = tokio::fs::remove_dir_all(&state.runtime_paths.runtime_dir).await;
    }

    #[tokio::test]
    async fn persist_effective_node_select_writes_volatile_layer() {
        use crate::models::{Config, NodeSelect, Region};
        use crate::test_support::app_state;

        let state = app_state(Config {
            node_select: NodeSelect::Fastest(Region::Hk),
            ..Config::default()
        });
        persist_effective_node_select(&state, NodeSelect::Manual)
            .await
            .unwrap();

        assert_eq!(state.config.read().await.node_select, NodeSelect::Manual);
        assert_eq!(
            *state.node_select_preference.read().await,
            NodeSelect::Fastest(Region::Hk),
            "effective fallback must not overwrite the requested strategy"
        );
        // 稳定层保留启动默认值；运行选择只写 volatile。
        let yaml = tokio::fs::read_to_string(&state.config_path).await.unwrap();
        assert!(yaml.contains("node_select: fastest_hk"));
        // 易变层落盘且可读回（manual 为默认覆盖）
        let loaded = load_volatile_config_at(&state.volatile_path)
            .await
            .expect("volatile file should exist");
        assert_eq!(loaded.node_select, NodeSelect::Manual);

        // 再写入非默认值，易变层显式记录
        persist_effective_node_select(&state, NodeSelect::Fastest(Region::Jp))
            .await
            .unwrap();
        let content = tokio::fs::read_to_string(&state.volatile_path)
            .await
            .unwrap();
        assert!(content.contains("node_select: fastest_jp"));

        let _ = tokio::fs::remove_file(&state.config_path).await;
        let _ = tokio::fs::remove_file(&state.volatile_path).await;
    }
}
